name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Fix SSH permissions
      run: |
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Configure SSH
      run: |
        echo -e "Host ${{ secrets.VM_HOST }}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Debug SSH connection
      run: ssh -vvv -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        script: |
          cd ~/nornikel_hack
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose up -d
