name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create SSH directory
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Fix SSH permissions
      run: |
        echo -e "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Configure SSH
      run: |
        echo -e "Host ${{ secrets.VM_HOST }}\n\tStrictHostKeyChecking no\n\tIdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
        chmod 600 ~/.ssh/config

    - name: Add host to known_hosts
      run: ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Set Docker Compose Timeout
      run: echo "COMPOSE_HTTP_TIMEOUT=600" >> $GITHUB_ENV    

    - name: Deploy and pass environment variables to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        port: 22
        timeout: 1h # Увеличиваем таймаут до 1 часа
        script: |
          # Переменные окружения
          echo "API_KEY=${{ secrets.API_KEY }}" >> ~/nornikel_hack/.env

          # Обновление кода и перезапуск
          cd ~/nornikel_hack
          git pull origin main
          docker-compose down
          docker-compose pull
          docker-compose build --no-cache
          docker-compose up -d
